#!/usr/bin/env python2

import os
import yaml

import qvarn


specdir = '/etc/qvarn/resources'


def version():
    return {
        'api': {
            'version': qvarn.__version__,
        },
        'implementation': {
            'name': 'Qvarn',
            'version': qvarn.__version__,
        },
    }


def setup_version_resource(app):
    vs = qvarn.VersionedStorage()
    vs.set_resource_type(u'version')
    app.add_versioned_storage(vs)

    resource = qvarn.SimpleResource()
    resource.set_path(u'/version', version)
    return resource


app = qvarn.BackendApplication()
resource = setup_version_resource(app)
app.add_routes([resource])
application = app.prepare_for_uwsgi(specdir)
